// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A Genkit flow for evaluating task content using a selected AI provider.
 *
 * - evaluateTaskContent - A function that handles the task content evaluation process.
 * - EvaluateTaskContentInput - The input type for the evaluateTaskContent function.
 * - EvaluateTaskContentOutput - The return type for the evaluateTaskContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EvaluateTaskContentInputSchema = z.object({
  taskContent: z.string().describe('The content of the task to be evaluated.'),
  aiProvider: z
    .enum(['OpenAI', 'Groq', 'Gemini', 'Claude', 'Ollama'])
    .describe('The AI provider to use for evaluation.'),
});
export type EvaluateTaskContentInput = z.infer<typeof EvaluateTaskContentInputSchema>;

const EvaluateTaskContentOutputSchema = z.object({
  aiScore: z.number().describe('The AI score for the task content.'),
  reasons: z.string().describe('The reasons for the AI score.'),
  suggestions: z.string().describe('Suggestions for improving the task content.'),
});
export type EvaluateTaskContentOutput = z.infer<typeof EvaluateTaskContentOutputSchema>;

export async function evaluateTaskContent(input: EvaluateTaskContentInput): Promise<EvaluateTaskContentOutput> {
  return evaluateTaskContentFlow(input);
}

const evaluateTaskContentPrompt = ai.definePrompt({
  name: 'evaluateTaskContentPrompt',
  input: {schema: EvaluateTaskContentInputSchema},
  output: {schema: EvaluateTaskContentOutputSchema},
  prompt: `You are an AI task evaluator. You will evaluate the task content provided by the user and provide an AI score, reasons for the score, and suggestions for improvement.

Task Content: {{{taskContent}}}

Provide the output in the following format:
{
  "aiScore": <AI Score>,
  "reasons": <Reasons for the score>,
  "suggestions": <Suggestions for improvement>
}`,
});

const evaluateTaskContentFlow = ai.defineFlow(
  {
    name: 'evaluateTaskContentFlow',
    inputSchema: EvaluateTaskContentInputSchema,
    outputSchema: EvaluateTaskContentOutputSchema,
  },
  async input => {
    const {output} = await evaluateTaskContentPrompt(input);
    return output!;
  }
);
